name: Deploy to Server

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to server
        run: |
          echo "${{ secrets.RS_SSH_PRIVATE_KEY }}" > /tmp/private_key.pem
          chmod 400 /tmp/private_key.pem
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -i /tmp/private_key.pem" dist/ ec2-user@ec2-34-235-14-121.compute-1.amazonaws.com:/home/ec2-user/hue-tint-studio
        env:
          RS_USER: ec2-user
