name: Deploy to Server

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to server
        run: |
          rsync -avz --delete dist/ ec2-user@ec2-54-210-133-52.compute-1.amazonaws.com:/home/ec2-user/hue-tint-studio
        env:
          RS_USER: ec2-user
          RS_SSH_PRIVATE_KEY: ${{ secrets.RS_SSH_PRIVATE_KEY }}
